app_code="myinvois"
bu="se"
env="dev"
owner="lh"
resource_group_name ="SEA-DEV-MYINVOIS-RG"
key_vault_id= "/subscriptions/bb03611c-e0e3-48f6-a773-6a9dc9f480cf/resourceGroups/SEA-DEV-MYINVOIS-RG/providers/Microsoft.KeyVault/vaults/SEA-DEV-MYINVOIS-KV"
